import { createTestProjectProfile } from 'realtime-server/lib/esm/scriptureforge/models/sf-project-test-data';
import { TranslateSource } from 'realtime-server/lib/esm/scriptureforge/models/translate-config';
import { DeltaOperation } from 'rich-text';
import { chapterDraftHasText, normalizeLanguageCodeToISO639_3, projectToDraftSources } from './draft-utils';

function translateSource(id: string): TranslateSource {
  return {
    projectRef: `SF${id}`,
    paratextId: `PT${id}`,
    writingSystem: { tag: 'en' },
    shortName: `TP${id}`,
    name: `Test Project ${id}`
  };
}

describe('DraftUtils', () => {
  describe('projectToDraftSources', () => {
    it('handles default project', () => {
      const testProject = createTestProjectProfile();
      const result = projectToDraftSources(testProject);
      expect(result).toEqual({ draftingSources: [], trainingSources: [], trainingTargets: [testProject] });
    });

    it('handles setting training and drafting sources', () => {
      const testSource = translateSource('test source');
      const testFirstDraftingSource = translateSource('test first drafting source');
      const testFirstTrainingSource = translateSource('test first training source');
      const testSecondTrainingSource = translateSource('test second training source');
      const testProject = createTestProjectProfile({
        translateConfig: {
          source: testSource,
          draftConfig: {
            draftingSources: [testFirstDraftingSource],
            trainingSources: [testFirstTrainingSource, testSecondTrainingSource]
          }
        }
      });

      const result = projectToDraftSources(testProject);
      expect(result).toEqual({
        draftingSources: [testFirstDraftingSource],
        trainingSources: [testFirstTrainingSource, testSecondTrainingSource],
        trainingTargets: [testProject]
      });
    });
  });

  describe('chapterDraftHasText', () => {
    const aiRemarkOps: DeltaOperation[] = [
      { insert: { chapter: { number: '3', style: 'c' } } },
      { insert: 'This draft of JON 3 was generated by AI.', attributes: { segment: 'rem_1' } },
      { insert: '\n', attributes: { para: { style: 'rem' } } }
    ];

    it('is false for a chapter that was not drafted', () => {
      expect(chapterDraftHasText(aiRemarkOps)).toBe(false);
    });

    it('is false for a chapter with no ops', () => {
      expect(chapterDraftHasText([])).toBe(false);
    });

    it('is false when the verses of the chapter are blank', () => {
      expect(
        chapterDraftHasText([
          ...aiRemarkOps,
          { insert: { verse: { number: '1', style: 'v' } } },
          { insert: { blank: true }, attributes: { segment: 'verse_3_1' } },
          { insert: '\n', attributes: { para: { style: 'p' } } }
        ])
      ).toBe(false);
    });

    it('is true when a verse of the chapter has text', () => {
      expect(
        chapterDraftHasText([
          ...aiRemarkOps,
          { insert: { verse: { number: '1', style: 'v' } } },
          { insert: 'But it displeased Jonah exceedingly.', attributes: { segment: 'verse_3_1' } },
          { insert: '\n', attributes: { para: { style: 'p' } } }
        ])
      ).toBe(true);
    });
  });
});

describe('normalizeLanguageCodeToISO639_3', () => {
  it('handles ISO 639-1 codes', () => {
    expect(normalizeLanguageCodeToISO639_3('en')).toBe('eng');
    expect(normalizeLanguageCodeToISO639_3('zh')).toBe('zho');
  });

  it('handles ISO 639-2 bibliography codes', () => {
    expect(normalizeLanguageCodeToISO639_3('fre')).toBe('fra');
    expect(normalizeLanguageCodeToISO639_3('chi')).toBe('zho');
  });

  it('handles codes with a region or script', () => {
    expect(normalizeLanguageCodeToISO639_3('en-US')).toBe('eng');
    expect(normalizeLanguageCodeToISO639_3('zh-CN')).toBe('zho');

    expect(normalizeLanguageCodeToISO639_3('zh-Hans')).toBe('zho');
    expect(normalizeLanguageCodeToISO639_3('en-Latn')).toBe('eng');

    expect(normalizeLanguageCodeToISO639_3('zh-Hans-CN')).toBe('zho');
    expect(normalizeLanguageCodeToISO639_3('en-Latn-US')).toBe('eng');
  });
});
